export const SET_INITIAL = 'SET_INITIAL';
export const SET_YEARS = 'SET_YEARS';
export const SET_RATE = 'SET_RATE';
export const SET_MONTHLY_OVERPAYMENT = 'SET_MONTHLY_OVERPAYMENT';
export const ADD_OVERPAYMENT = 'ADD_OVERPAYMENT';
export const DELETE_OVERPAYMENT = 'DELETE_OVERPAYMENT';


